import {
  cancelPendingWithdrawal,
  createWalletTransaction,
  deleteLinkedPayoutAccount,
  getTopUpConversionPreview,
  getTopUpLimits,
  getWallet,
  getWalletAnalyticsSeries,
  listLinkedPayoutAccounts,
  listWalletTransactions,
  retryFailedWithdrawal,
  setDefaultLinkedPayoutAccount,
  topUpWallet,
  upsertLinkedPayoutAccount,
  verifyPayoutAccount,
  withdrawFromWallet,
} from '../repositories/walletRepository';

export const walletService = {
  getWallet,
  listWalletTransactions,
  listLinkedPayoutAccounts,
  getWalletAnalyticsSeries,
  getTopUpConversionPreview,
  getTopUpLimits,
  createWalletTransaction,
  topUpWallet,
  withdrawFromWallet,
  upsertLinkedPayoutAccount,
  deleteLinkedPayoutAccount,
  setDefaultLinkedPayoutAccount,
  verifyPayoutAccount,
  cancelPendingWithdrawal,
  retryFailedWithdrawal,
};
